name: Build, Package, Release (main)
'on':
  release:
    types:
      - created
  push:
    branches:
      - main
env:
  VERSION: null
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: get semversion
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.MO_REGISTRY_AUTH_URL__MAIN }}
          username: ${{ vars.MO_REGISTRY_USER__MAIN }}
          password: ${{ secrets.MO_REGISTRY_PAT__MAIN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ${{ vars.MO_DOCKERCONTEXT__MAIN }}
          file: ${{ vars.MO_DOCKERFILE__MAIN }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.MO_IMAGE_NAME__MAIN }}:${{ env.VERSION }}
            ${{ vars.MO_IMAGE_NAME__MAIN }}:latest
          build-args: |
            VERSION=${{ env.VERSION }}
      - id: releaseWithMogenius-a2da82a0fd885d96b0f1
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: true
          image: ${{ vars.MO_IMAGE_NAME__MAIN }}:${{ env.VERSION }}
          kind: Deployment
          namespace: kube-public
          resourceName: ang-l
          containerName: ang-l
          keyKind: ${{ vars.MO_API_KIND__MAIN }}
          token: ${{ secrets.MO_API_TOKEN__a2da82a0fd885d96b0f1__MAIN }}
      - id: releaseWithMogenius-f781f548dc3221edf0eb
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: true
          image: ${{ vars.MO_IMAGE_NAME__MAIN }}:${{ env.VERSION }}
          kind: Deployment
          namespace: mogenius
          resourceName: angularmog
          containerName: angularmog
          keyKind: ${{ vars.MO_API_KIND__MAIN }}
          token: ${{ secrets.MO_API_TOKEN__f781f548dc3221edf0eb__MAIN }}
      - id: releaseWithMogenius-2ae488531c6c44b17cb0
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: true
          image: ${{ vars.MO_IMAGE_NAME__MAIN }}:${{ env.VERSION }}
          kind: Deployment
          namespace: mogenius
          resourceName: ang123
          containerName: ang123
          keyKind: ${{ vars.MO_API_KIND__MAIN }}
          token: ${{ secrets.MO_API_TOKEN__2ae488531c6c44b17cb0__MAIN }}
